export type StoreLocale = "en" | "rw";

const EN = {
  how: "How it works",
  signIn: "Sign in",
  listBirds: "List a flock",
  forFarmsLine: "Got birds to sell?",
  needBirds: "Need birds",
  gotBirds: "Got birds",
  gotBirdsAsk: "For farms",
  navRequest: "Request",
  buyers: "Buyers",
  needBirdsWho: "Butchers, restaurants, hotels",
  gotBirdsWho: "Farms",
  buyInstead: "Need birds this week?",
  live: "Live across Rwanda",
  landingHero: "Need birds this week?",
  landingSub: "Tell us how many.",
  request: "Request birds",
  requestThese: "Request these birds",
  sendRequest: "Request birds",
  sending: "Sending…",
  thisWeek: "This week",
  nextWeek: "Next week",
  later: "Later",
  anyWeek: "Any week",
  anyService: "Any service",
  filterWeek: "Week",
  filterService: "Service",
  filters: "Filters",
  done: "Done",
  slaughter: "Slaughter",
  delivery: "Delivery",
  tripHelp: "Slaughter adds a per-bird fee. Off means live birds. Delivery is a separate trip charge.",
  requiredMark: "*",
  readyNow: "Ready now",
  allLots: "Live lots",
  emptyTitle: "The next flocks are coming in.",
  emptyBody: "Leave your number. Cleva matches you and calls you back.",
  requestIn: "Request received",
  name: "Your name",
  phone: "Phone",
  business: "Business name",
  buyerType: "I am a",
  butcher: "Butcher",
  restaurant: "Restaurant",
  hotel: "Hotel",
  vendor: "Vendor",
  other: "Other",
  birdsNeeded: "How many this trip",
  neededFrom: "Needed from",
  whenNeeded: "When",
  aDate: "A date",
  shopDetail: "More about your shop",
  usualWeek: "Usual week (birds)",
  settleHow: "How you settle",
  settleCash: "Cash at the scale",
  settleSame: "Same week",
  settle7: "7 days",
  settle14: "14 days",
  expectPay: "What you expect to pay",
  expectBoard: "This week’s board",
  expectUnder: "Under",
  rwfKg: "RWF/kg",
  handover: "How you get them",
  collect: "Collect",
  processHow: "Live or slaughtered",
  processLive: "Live",
  liveCollectHint: "Live birds — you collect after you pay.",
  liveDeliveryHint: "Live delivery only if the farm offers it.",
  farmDelivers: "Farm delivers",
  foodserviceMin: "From 10 birds. Small kitchens pay Kitchen rate.",
  collectOnlyHint: "You collect at the farm after you pay.",
  chipCollectLive: "Collect · Live",
  chipSlaughter: "Slaughter",
  chipFarmDelivery: "Farm delivery",
  needClevaDelivery: "Need delivery help",
  needClevaDeliveryDone: "Asked Cleva for delivery help",
  clevaDelivers: "Cleva delivery",
  createAccountLots: "Create an account to see lots",
  createAccount: "Create an account",
  message: "Note for Cleva",
  district: "District",
  province: "Province",
  selectProvince: "Select province",
  selectDistrict: "Select district",
  pickProvince: "Pick a province first",
  allProvinces: "All provinces",
  allDistricts: "All districts",
  sortReady: "Ready soonest",
  sortBirds: "Most birds",
  sortPrice: "Lowest price",
  clevaRun: "Cleva-run",
  thisTrip: "This trip",
  shopTier: "Shop",
  usualTier: "Usual trip",
  loadTier: "Load",
  moreThisWeek: "More this week — request, we match",
  unlockNext: "more birds unlocks",
  perKg: "RWF/kg",
  tripKg: "kg",
  verified: "Verified",
  brokered: "Booked through Cleva",
  birds: "birds",
  ready: "Ready",
  weight: "Weight",
  pickup: "Collect",
  partnerBanner: "You already have a buyer account.",
  openMarket: "Open your orders",
  storeBrand: "Cleva Market",
  footerContact: "Cleva Technologies · Rwanda",
  footerBlurb: "Weekly poultry board. Rwanda.",
  footerMarket: "Market",
  footerTalk: "Talk to Cleva",
  howTitle: "How it works",
  howMarket: "How the market works",
  listingsThisWeek: "Open listings",
  requestLot: "Request birds",
  boardHow1t: "Farms list",
  boardHow1: "Bird count and average kg. Cleva verifies the flock before it goes on the board.",
  boardHow2t: "Buyers request",
  boardHow2: "Open listings show district, birds, and this week’s rate. Request from the card.",
  boardHow3t: "Meet at the scale",
  boardHow3: "Pay Cleva to confirm. Birds are weighed. The split on the offer is what you pay.",
  howSub: "You send the trip. Cleva matches and calls. Pay Cleva to confirm.",
  how1t: "See what is ready",
  how1: "Live lots show district, birds left, ready window, and the Cleva price for your trip. Farm names stay with Cleva until a booking.",
  how2t: "Request in one minute",
  how2: "Name, phone, how many birds. Pay Cleva to confirm. We pay the farm.",
  how3t: "Cleva confirms",
  how3: "We match you to the farm after pay, confirm live collect or slaughter, and check weight on handover.",
  how4t: "Partners book faster",
  how4: "Verified buyers see exact RWF/kg and reserve instantly.",
  landingHow1t: "You send the trip",
  landingHow1: "Count and when. We take it from there.",
  landingHow2t: "Cleva matches and calls",
  landingHow2: "A person matches a flock and phones this number.",
  landingHow3t: "Pay Cleva",
  landingHow3: "The order is confirmed when Cleva is paid. We pay the farm.",
  formFooterBuy: "Pay Cleva to confirm. The farm is paid after.",
  formFooterSell: "No software account. Cleva lists after a check.",
  sellTitle: "Your birds, in front of buyers.",
  sellSub: "Leave a number. Cleva lists the flock. No software account.",
  sell1: "You leave the flock",
  sell1b: "Birds and average kg. That is enough.",
  sell2: "Cleva checks",
  sell2b: "We verify the flock before it goes on the board.",
  sell3: "Buyers see this week",
  sell3b: "This week and next week. You get the board rate at the scale.",
  trustNoAccount: "No account",
  trustWeCall: "We call you",
  trustPayScale: "Pay Cleva",
  trustLeaveNumber: "Leave a number",
  trustListAfterCheck: "We list after a check",
  trustNoSoftware: "No software account",
  faqTitle: "Questions",
  faqPayQ: "Do I pay here?",
  faqPayA: "Partners pay Cleva to confirm the order. We then pay the farm. The split is on the offer.",
  faqAccountQ: "Do I need an account?",
  faqAccountA: "A buyer account lets you track orders and book faster. You can still send a request now.",
  faqProcessQ: "Live or slaughtered?",
  faqProcessA:
    "Live birds default to collect after you pay — you arrange transport. Slaughtered birds can add farm delivery for a trip fee when the farm offers it.",
  faqDeliveryQ: "Do you deliver live birds?",
  faqDeliveryA:
    "Usually you collect. Farm delivery is only when the farm opted in. Cleva does not run a self-serve live courier.",
  faqEmptyQ: "What if nothing is listed?",
  faqEmptyA: "We match a flock and call you.",
  faqTakeQ: "What does Cleva take?",
  faqTakeA: "A commission on the meat line. You see it on the offer before you list. Final at the scale.",
  faqWhenSeenQ: "When do buyers see my birds?",
  faqWhenSeenA: "After Cleva checks the flock. Then they show this week and next week.",
  faqFarmAppQ: "Do I need the farm app?",
  faqFarmAppA: "No. Leave a number here. The farm software is optional if you want to run the flock yourself.",
  proofBirdsWeek: "birds this week",
  proofFarms: "verified farms",
  proofDistricts: "districts",
  birdsForSale: "How many birds",
  sellOsHint: "Want the farm software?",
  sellOsLink: "Open a Cleva Farm account",
  farmsTitle: "Farms that chose to be seen",
  farmsEmpty: "No public farm pages yet.",
  farmsEmptyHint: "Farms appear here after they publish a storefront.",
  noMatches: "Nothing in that slice. Clear filters or leave a request.",
  clear: "Clear filters",
  loadMore: "Show more lots",
  nextSteps: "What happens next",
  back: "Back to market",
  missingLot: "This lot is no longer on the market.",
  priceOnRequest: "Price on request",
  currentLots: "Birds on this farm",
  farmMissing: "This farm is not public right now.",
  close: "Close",
  ok: "OK",
  yourRef: "Your reference",
  willCall: "Cleva will call you.",
  sortBy: "Sort",
  laterWeek: "Later",
  lotsCount: "lots",
  callFarm: "Call farm",
  youReceive: "You receive",
  meatLine: "Meat",
  commissionLine: "Cleva commission",
  processingLine: "Processing",
  finalAtScale: "This rate on the kg at the scale.",
  rateUntil: "This week’s rate until",
  avgKg: "Average kg",
  thisWeeksBoard: "This week’s Cleva board",
  fromPerKg: "from",
  youPay: "You pay",
  slaughterFee: "Slaughter",
  deliveryFee: "Farm delivery",
  perBird: "bird",
  offerWhenPosted: "You-receive appears when this week’s board is up.",
  holdThisRate: "Leave a number to hold this week’s rate.",
  indicativeUntilScale: "Indicative until both sides confirm kg.",
  ratePosted: "This week’s Cleva rate",
  stripAsk: "Tell us how many.",
  rateHow: "Cleva posts this week’s buyer rate. Not a live auction.",
  boardFills: "Board fills as farms list this week.",
  lotOpen: "Open",
  vsLastWeek: "vs last week",
  waCleva: "Message Cleva on WhatsApp",
  waFab: "Chat with us",
  waPrefill: "I need birds this week.",
  splitFarmer: "To the farm",
  splitService: "Cleva service",
  splitProcessing: "Processing",
  splitTransport: "Transport",
  splitFarmDelivery: "Farm delivery",
  splitClevaDelivery: "Cleva delivery",
  splitFarmGross: "Birds at farm-gate",
  splitFarmService: "Cleva service",
  splitFarmVisit: "Visit / weigh",
  splitFarmProcessing: "Processing",
  splitYouPay: "You pay Cleva",
  splitYouReceive: "You receive",
  splitSee: "What's in this price",
  payToConfirm: "Pay to confirm",
  paySent: "I've sent the payment",
  payPending: "Waiting for Cleva to confirm payment",
  payPaid: "Paid · order confirmed",
  payFarmerDue: "Cleva pays you after the buyer pays",
  payFarmerPaid: "Paid out",
  payInstructions: "Send this amount to Cleva. The order is confirmed when payment lands.",
  payRef: "Payment reference",
  payPhone: "Your MoMo number",
  awaitingPay: "Awaiting payment",
  farmerEmptyTitle: "Put your birds on the book",
  farmerEmptyBody: "Cleva sets this week’s board price. A scout visits before the selling week. Buyers pay Cleva. Cleva pays you.",
  farmerEmptyHow1: "Cleva sets the board price",
  farmerEmptyHow2: "A scout visits before selling week",
  farmerEmptyHow3: "Buyer pays Cleva to confirm",
  farmerEmptyHow4: "Cleva pays you",
  farmerOrdersEmptyTitle: "No paid orders yet",
  farmerOrdersEmptyBody: "When a buyer pays Cleva for your birds, the order shows here. Until then, nothing to do.",
  farmerFarmPageEmptyTitle: "List birds first",
  farmerFarmPageEmptyBody: "Name your farm after you have a listing. Buyers see district, birds, kg, and the Cleva price — not a shop page.",
  farmerYourMoney: "Your money",
  farmerOnTheBook: "On the book",
  farmerAskKg: "Ask RWF/kg",
  farmerAskBoard: "This is Cleva’s week. You can ask inside the rail.",
  farmerAskOutOfRail: "Outside the rail this listing waits for review and stays off the board.",
  farmerVisitHelp: "Someone from Cleva will visit before this week to confirm the flock and average weight.",
  farmerNavListings: "Listings",
  farmerNavOrders: "Orders",
  farmerNavFarmPage: "Farm page",
  farmerListBirds: "List birds",
  farmerWhatPublicSees: "What buyers see",
  farmerSellingWeek: "Selling week",
  farmerPutOnBook: "Put on the book",
};

const RW: typeof EN = {
  how: "Uko bikora",
  signIn: "Injira",
  listBirds: "Andika ishyo",
  forFarmsLine: "Ufite inkoko zo kugurisha?",
  needBirds: "Ukeneye inkoko",
  gotBirds: "Ufite inkoko",
  gotBirdsAsk: "Ku birima",
  navRequest: "Saba",
  buyers: "Abaguzi",
  needBirdsWho: "Abacuzi, resitora, hoteli",
  gotBirdsWho: "Ibirima",
  buyInstead: "Ukeneye inkoko muri iki cyumweru?",
  live: "Ku isi yose mu Rwanda",
  landingHero: "Ukeneye inkoko muri iki cyumweru?",
  landingSub: "Tubwire umubare.",
  request: "Saba inkoko",
  requestThese: "Saba izi nkoko",
  sendRequest: "Saba inkoko",
  sending: "Birimo koherezwa…",
  thisWeek: "Iki cyumweru",
  nextWeek: "Icyumweru gitaha",
  later: "Nyuma",
  anyWeek: "Icyumweru icyo aricyo cyose",
  anyService: "Serivisi zose",
  filterWeek: "Icyumweru",
  filterService: "Serivisi",
  filters: "Muyungurura",
  done: "Byakozwe",
  slaughter: "Kubaga",
  delivery: "Gutanga",
  tripHelp: "Kubaga byongera amafaranga ku nkoko. Zizima? Hagarika. Gutanga ni ikindi giciro cy'urugendo.",
  requiredMark: "*",
  readyNow: "Ziteguye nonaha",
  allLots: "Inkoko ziri ku isoko",
  emptyTitle: "Amashyo akurikira araza.",
  emptyBody: "Siga numero yawe. Cleva iraguhuza ikakuhamagara.",
  requestIn: "Icyifuzo cyakiriwe",
  name: "Izina ryawe",
  phone: "Telefoni",
  business: "Izina ry'ubucuruzi",
  buyerType: "Ndi",
  butcher: "Ubacuzi",
  restaurant: "Resitora",
  hotel: "Hoteli",
  vendor: "Umucuruzi",
  other: "Ikindi",
  birdsNeeded: "Zinga muri uru rugendo",
  neededFrom: "Uzi keneye kuva",
  whenNeeded: "Ryari",
  aDate: "Itariki",
  shopDetail: "Ibindi ku iduka ryawe",
  usualWeek: "Muri icyumweru (inkoko)",
  settleHow: "Wishyura gute",
  settleCash: "Amafaranga ku bipimo",
  settleSame: "Muri icyo cyumweru",
  settle7: "Iminsi 7",
  settle14: "Iminsi 14",
  expectPay: "Uteganya kwishyura",
  expectBoard: "Ikibaho cy'iki cyumweru",
  expectUnder: "Munsi ya",
  rwfKg: "RWF/kg",
  handover: "Uko uzibona",
  collect: "Gufata",
  processHow: "Zizima cyangwa zabazwe",
  processLive: "Zizima",
  liveCollectHint: "Zizima — ugafata nyuma yo kwishyura.",
  liveDeliveryHint: "Gutanga zizima ni iyo umurima abishoboye.",
  farmDelivers: "Umurima utanga",
  foodserviceMin: "Kuva kuri 10. Resitora nto zishyura igiciro cya Kitchen.",
  collectOnlyHint: "Ugafata ku murima nyuma yo kwishyura.",
  chipCollectLive: "Gufata · Zizima",
  chipSlaughter: "Kubaga",
  chipFarmDelivery: "Umurima utanga",
  needClevaDelivery: "Ukeneye ubufasha bwo gutanga",
  needClevaDeliveryDone: "Wasabye Cleva ubufasha bwo gutanga",
  clevaDelivers: "Cleva itanga",
  createAccountLots: "Fungura konti urebe inkoko",
  createAccount: "Fungura konti",
  message: "Ubutumwa kuri Cleva",
  district: "Akarere",
  province: "Intara",
  selectProvince: "Hitamo intara",
  selectDistrict: "Hitamo akarere",
  pickProvince: "Hitamo intara mbere",
  allProvinces: "Intara zose",
  allDistricts: "Uturere twose",
  sortReady: "Ziteguye vuba",
  sortBirds: "Inkoko nyinshi",
  sortPrice: "Igiciro gito",
  clevaRun: "Cleva-run",
  thisTrip: "Uru rugendo",
  shopTier: "Agaduka",
  usualTier: "Urugendo rusanzwe",
  loadTier: "Umutwaro",
  moreThisWeek: "Izindi muri iki cyumweru — saba, turahura",
  unlockNext: "inkoko zisaba",
  perKg: "RWF/kg",
  tripKg: "kg",
  verified: "Byasuzumwe",
  brokered: "Bikoreshwa na Cleva",
  birds: "inkoko",
  ready: "Igihe",
  weight: "Ibiro",
  pickup: "Gufata",
  partnerBanner: "Usanzwe ufite konti y'umuguzi.",
  openMarket: "Fungura ibyo wasabye",
  storeBrand: "Cleva Market",
  footerContact: "Cleva Technologies · Rwanda",
  footerBlurb: "Ikibaho cy'inkoko cy'icyumweru. Rwanda.",
  footerMarket: "Isoko",
  footerTalk: "Vugana na Cleva",
  howTitle: "Uko bikora",
  howMarket: "Uko isoko ikora",
  listingsThisWeek: "Amashyo afunguye",
  requestLot: "Saba inkoko",
  boardHow1t: "Ibirima byandika",
  boardHow1: "Umubare w'inkoko n'ibiro. Cleva yemeza ishyo mbere yo kugishyira ku kibaho.",
  boardHow2t: "Abaguzi basaba",
  boardHow2: "Amashyo afunguye yerekana akarere, umubare, n'igiciro cy'iki cyumweru. Saba ku ifishi.",
  boardHow3t: "Muhura ku bipimo",
  boardHow3: "Ishyura Cleva wemeze. Inkoko zipimwa. Isplit ku ifishi nicyo wishyura.",
  howSub: "Wohereza urugendo. Cleva irahura ikakuhamagara. Ishyura Cleva wemeze.",
  how1t: "Reba iziteguye",
  how1: "Ubona akarere, umubare, igihe, n'igiciro cya Cleva ku rugendo rwawe. Izina ry'umurima riguma kuri Cleva kugeza ubuhamagaro.",
  how2t: "Saba mu munota umwe",
  how2: "Izina, telefoni, umubare w'inkoko. Ishyura Cleva wemeze. Tishyura umurima.",
  how3t: "Cleva yemeza",
  how3: "Duhuje n'umurima nyuma yo kwishyura, twemeza gufata cyangwa kubaga, kandi tureba ibiro iyo bihabwa.",
  how4t: "Abafatanyabikorwa babika vuba",
  how4: "Abaguzi basuzumwe babona igiciro nyacyo maze babika ako kanya.",
  landingHow1t: "Wohereza urugendo",
  landingHow1: "Umubare n'igihe. Tugitwara.",
  landingHow2t: "Cleva irahura ikakuhamagara",
  landingHow2: "Umuntu ahura n'ishyo akahamagara iyi numero.",
  landingHow3t: "Ishyura Cleva",
  landingHow3: "Ubutumire bwemezwa Cleva yishyuwe. Tishyura umurima.",
  formFooterBuy: "Ishyura Cleva wemeze. Umurima wishyurwa nyuma.",
  formFooterSell: "Nta konti ya porogaramu. Cleva yandika nyuma yo kugenzura.",
  sellTitle: "Inkoko zawe, imbere y'abaguzi.",
  sellSub: "Siga numero. Cleva yandika ishyo. Nta konti ya porogaramu.",
  sell1: "Usiga ishyo",
  sell1b: "Umubare n'ibiro. Bihagije.",
  sell2: "Cleva iragenzura",
  sell2b: "Tugenzura ishyo mbere yo kujya ku kibaho.",
  sell3: "Abaguzi babona iki cyumweru",
  sell3b: "Iki cyumweru n'icyo gitaha. Wakira igiciro cy'ikibaho ku bipimo.",
  trustNoAccount: "Nta konti",
  trustWeCall: "Turakuhamagara",
  trustPayScale: "Ishyura Cleva",
  trustLeaveNumber: "Siga numero",
  trustListAfterCheck: "Turandika nyuma yo kugenzura",
  trustNoSoftware: "Nta konti ya porogaramu",
  faqTitle: "Ibibazo",
  faqPayQ: "Wishyura hano?",
  faqPayA: "Abafatanyabikorwa bishyura Cleva kugira ngo ubutumire bwemezwe. Tishyura umurima. Isplit iri ku ifishi.",
  faqAccountQ: "Ukeneye konti?",
  faqAccountA: "Konti y'umuguzi igufasha gukurikirana ibisabwa no kubika vuba. Ushobora gusaba noneho.",
  faqProcessQ: "Zizima cyangwa zabazwe?",
  faqProcessA:
    "Inkoko zizima zisanzwe zifatwa nyuma yo kwishyura — witegura gutwara. Zabazwe zishobora kongeraho gutanga kwa murima iyo umurima ubyemera.",
  faqDeliveryQ: "Mutanga inkoko zizima?",
  faqDeliveryA:
    "Ubusanzwe ugafata. Gutanga kwa murima ni iyo umurima yemeye. Cleva ntabwo ifite courier ya live ku giti cye.",
  faqEmptyQ: "Niba nta n'imwe iri ku isoko?",
  faqEmptyA: "Duhura n'ishyo tukakuhamagara.",
  faqTakeQ: "Cleva ifata iki?",
  faqTakeA: "Komisiyo ku nyama. Uyibona ku ifishi mbere yo kwandika. Birangira ku bipimo.",
  faqWhenSeenQ: "Abaguzi babona inkoko ryari?",
  faqWhenSeenA: "Nyuma yo kugenzura ishyo. Hanyuma bigaragara iki cyumweru n'icyo gitaha.",
  faqFarmAppQ: "Ukeneye porogaramu y'umurima?",
  faqFarmAppA: "Oya. Siga numero hano. Porogaramu ni iyo ushaka gukoresha umurima wawe.",
  proofBirdsWeek: "inkoko muri iki cyumweru",
  proofFarms: "ibirima byasuzumwe",
  proofDistricts: "uturere",
  birdsForSale: "Inkoko zingana",
  sellOsHint: "Ukeneye porogaramu y'umurima?",
  sellOsLink: "Fungura konti ya Cleva Farm",
  farmsTitle: "Inganda zahisemo kugaragara",
  farmsEmpty: "Nta n'umurima ugaragara nonaha.",
  farmsEmptyHint: "Inganda zigaragara hano nyuma yo gushyira ahagaragara.",
  noMatches: "Nta cyabonetse muri izo miterere. Siba cyangwa usabe.",
  clear: "Siba filter",
  loadMore: "Erekana izindi",
  nextSteps: "Ibikurikira",
  back: "Subira ku isoko",
  missingLot: "Iyi lot ntabwo ikiri ku isoko.",
  priceOnRequest: "Igiciro kirabazwa",
  currentLots: "Inkoko ziri kuri uyu murima",
  farmMissing: "Uyu murima ntabwo ugaragara.",
  close: "Funga",
  ok: "Sawa",
  yourRef: "Kode yawe",
  willCall: "Cleva irakuhamagara.",
  sortBy: "Gutondeka",
  laterWeek: "Nyuma",
  lotsCount: "amashyo",
  callFarm: "Hamagara umurima",
  youReceive: "Wakira",
  meatLine: "Inyama",
  commissionLine: "Komisiyo ya Cleva",
  processingLine: "Gutunganya",
  finalAtScale: "Iki giciro ku kilo dupima ku mizani.",
  rateUntil: "Igiciro cy'iki cyumweru kigeza",
  avgKg: "Ibiro (kg)",
  thisWeeksBoard: "Ikibaho cya Cleva cy'iki cyumweru",
  fromPerKg: "kuva",
  youPay: "Wishyura",
  slaughterFee: "Kubaga",
  deliveryFee: "Umurima utanga",
  perBird: "inkoko",
  offerWhenPosted: "Amafaranga wakira agaragara iyo ikibaho cy'iki cyumweru gishyizweho.",
  holdThisRate: "Siga numero ugumane igiciro cy'iki cyumweru.",
  indicativeUntilScale: "Birangira iyo bombi bemera ibiro.",
  ratePosted: "Igiciro cya Cleva cy'iki cyumweru",
  stripAsk: "Tubwire umubare.",
  rateHow: "Cleva ishyira igiciro cy'umuguzi cy'iki cyumweru. Siyo iraha igezweho.",
  boardFills: "Ikibaho cyuzura iyo ibirima byanditse muri iki cyumweru.",
  lotOpen: "Irafunguye",
  vsLastWeek: "ugereranyije n'icyumweru gishize",
  waCleva: "Andikira Cleva kuri WhatsApp",
  waFab: "Tuvugishe",
  waPrefill: "Nkeneye inkoko muri iki cyumweru.",
  splitFarmer: "Ku murima",
  splitService: "Serivisi ya Cleva",
  splitProcessing: "Kubaga",
  splitTransport: "Gutanga",
  splitFarmDelivery: "Umurima utanga",
  splitClevaDelivery: "Cleva itanga",
  splitFarmGross: "Inkoko ku giciro cy'umurima",
  splitFarmService: "Serivisi ya Cleva",
  splitFarmVisit: "Gusura / gupima",
  splitFarmProcessing: "Kubaga",
  splitYouPay: "Wishyura Cleva",
  splitYouReceive: "Wakira",
  splitSee: "Ibiri muri iki giciro",
  payToConfirm: "Ishyura wemeze",
  paySent: "Nohereje amafaranga",
  payPending: "Tegereza Cleva yemeze kwishyura",
  payPaid: "Byishyuwe · ubutumire bwemejwe",
  payFarmerDue: "Cleva irakwishyura nyuma y'umuguzi",
  payFarmerPaid: "Byishyuwe",
  payInstructions: "Ohereza aya mafaranga kuri Cleva. Ubutumire bwemezwa amafaranga amaze kugera.",
  payRef: "Referansi y'ishyura",
  payPhone: "Numero yawe ya MoMo",
  awaitingPay: "Gutegereza kwishyura",
  farmerEmptyTitle: "Shyira inkoko zawe ku gitabo",
  farmerEmptyBody: "Cleva ishyira igiciro cy'iki cyumweru. Umujyanama asura mbere y'icyumweru cyo kugurisha. Umuguzi yishyura Cleva. Cleva irakwishyura.",
  farmerEmptyHow1: "Cleva ishyira igiciro cy'ikibaho",
  farmerEmptyHow2: "Umujyanama asura mbere y'icyumweru cyo kugurisha",
  farmerEmptyHow3: "Umuguzi yishyura Cleva yemeze",
  farmerEmptyHow4: "Cleva irakwishyura",
  farmerOrdersEmptyTitle: "Nta butumire bwishyuwe",
  farmerOrdersEmptyBody: "Iyo umuguzi yishyuye Cleva ku nkoko zawe, ubutumire bigaragara hano. Kugeza ubwo, nta cyo ukora.",
  farmerFarmPageEmptyTitle: "Andika inkoko mbere",
  farmerFarmPageEmptyBody: "Izina ry'umurima rirasigara nyuma yo kwandika. Abaguzi babona akarere, umubare, ibiro, n'igiciro cya Cleva — ntabwo ari ipaji y'iduka.",
  farmerYourMoney: "Amafaranga yawe",
  farmerOnTheBook: "Ku gitabo",
  farmerAskKg: "Usaba RWF/kg",
  farmerAskBoard: "Iki ni icyumweru cya Cleva. Urashobora gusaba mu nkombe.",
  farmerAskOutOfRail: "Hanze y'inkombe iri shyiraho rirategereza isuzuma kandi ntirigaragare ku gitabo.",
  farmerVisitHelp: "Umuntu wa Cleva azasura mbere y'iki cyumweru kugenzura ishyo n'ibiro.",
  farmerNavListings: "Amashyo",
  farmerNavOrders: "Ibisabwa",
  farmerNavFarmPage: "Ipaji y'umurima",
  farmerListBirds: "Andika inkoko",
  farmerWhatPublicSees: "Icyo abaguzi babona",
  farmerSellingWeek: "Icyumweru cyo kugurisha",
  farmerPutOnBook: "Shyira ku gitabo",
}

export function storeCopyKeys(): Array<keyof typeof EN> {
  return Object.keys(EN) as Array<keyof typeof EN>;
}

export function storeT(locale: StoreLocale, key: keyof typeof EN): string {
  return (locale === "rw" ? RW : EN)[key];
}
