/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["selector", "[data-theme='dark']"],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Bricolage Grotesque"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['"DM Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"DM Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      spacing: {
        "shell-x": "var(--space-shell-x)",
        "shell-y": "var(--space-shell-y)",
        section: "var(--space-section)",
        stack: "var(--space-stack)",
        card: "var(--space-card)",
        "title-gap": "var(--space-title-gap)",
      },
      colors: {
        surface: "var(--surface-color)",
        "surface-card": "var(--surface-card)",
        "surface-elevated": "var(--surface-elevated)",
        "surface-subtle": "var(--surface-subtle)",
        "app-bg": "var(--background-color)",
        "app-border": "var(--border-color)",
        "app-text": "var(--text-primary)",
        "app-text-2": "var(--text-secondary)",
        "app-text-muted": "var(--text-muted)",
        "app-primary": "var(--primary-color)",
        "app-primary-soft": "var(--primary-color-soft)",
        "chart-bg": "var(--chart-bg)",
        "status-success": "var(--status-success)",
        "status-success-soft": "var(--status-success-soft)",
        "status-warning": "var(--status-warning)",
        "status-warning-soft": "var(--status-warning-soft)",
        "status-danger": "var(--status-danger)",
        "status-danger-soft": "var(--status-danger-soft)",
        "status-info": "var(--status-info)",
        "status-info-soft": "var(--status-info-soft)",
        "status-neutral": "var(--status-neutral)",
        "status-neutral-soft": "var(--status-neutral-soft)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        soft: "var(--shadow-soft)",
        elevated: "var(--shadow-elevated)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        control: "var(--radius-control)",
      },
      minHeight: {
        "control-sm": "var(--control-h-sm)",
        "control-md": "var(--control-h-md)",
        "control-lg": "var(--control-h-lg)",
        "control-field": "var(--control-h-field)",
      },
      height: {
        "control-sm": "var(--control-h-sm)",
        "control-md": "var(--control-h-md)",
        "control-lg": "var(--control-h-lg)",
        "control-field": "var(--control-h-field)",
      },
      width: {
        "control-sm": "var(--control-h-sm)",
        "control-md": "var(--control-h-md)",
        "control-lg": "var(--control-h-lg)",
        "control-field": "var(--control-h-field)",
      },
      animation: {
        "fade-up": "fade-in-up 350ms ease both",
        "live-pulse": "live-pulse 2s ease-in-out infinite",
        count: "count-up 300ms cubic-bezier(0.175, 0.885, 0.32, 1.275) both",
      },
    },
  },
  plugins: [],
};
